<#
.SYNOPSIS
    One-Command Windows 11 Claude Code Setup - MEGA INSTALLER

.DESCRIPTION
    This script does EVERYTHING to set up your Windows machine with Claude Code:
    - Installs WSL2 (Ubuntu Linux)
    - Installs all dev tools (Node.js, Python, git, etc.)
    - Installs Claude Code CLI
    - Sets up Windows Terminal with Catppuccin theme
    - Copies all your Mac configs
    - Installs all custom Claude agents

    Just run this ONE script and walk away for 15 minutes!

.NOTES
    Author: Claude Code
    Date: 2025-01-12
    Requirements: Windows 11, Administrator privileges, Internet connection
#>

#Requires -RunAsAdministrator

$ErrorActionPreference = "Continue"
$ProgressPreference = "SilentlyContinue"

# Color functions
function Write-Success { Write-Host $args -ForegroundColor Green }
function Write-Info { Write-Host $args -ForegroundColor Cyan }
function Write-Warning { Write-Host $args -ForegroundColor Yellow }
function Write-Error-Custom { Write-Host $args -ForegroundColor Red }

# Banner
Clear-Host
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "    WINDOWS 11 CLAUDE CODE - MEGA INSTALLER                           " -ForegroundColor Cyan
Write-Host "    One Command to Rule Them All                                       " -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Step 1: Install WSL2
Write-Info "━━━ STEP 1/7: Installing WSL2 (Ubuntu Linux) ━━━"
Write-Host ""

$wslInstalled = wsl --list 2>&1 | Select-String "Ubuntu"

if ($wslInstalled) {
    Write-Success "✓ WSL2 already installed"
} else {
    Write-Info "Installing WSL2 with Ubuntu..."

    try {
        wsl --install -d Ubuntu
        Write-Success "✓ WSL2 installed successfully"
        Write-Warning ""
        Write-Warning "⚠️  REBOOT REQUIRED!"
        Write-Warning "After reboot, run this script again to complete setup."
        Write-Warning ""

        $reboot = Read-Host "Reboot now? (y/n)"
        if ($reboot -eq "y") {
            Restart-Computer -Force
        }
        exit 0
    } catch {
        Write-Error-Custom "✗ Failed to install WSL2: $_"
        Write-Info "Try manually: wsl --install"
        exit 1
    }
}

Write-Host ""

# Step 2: Configure Windows Terminal
Write-Info "━━━ STEP 2/7: Configuring Windows Terminal ━━━"
Write-Host ""

$wtSettingsPath = "$env:LOCALAPPDATA\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"

if (Test-Path ".\windows-terminal\settings.json") {
    Write-Info "Backing up existing Windows Terminal settings..."
    if (Test-Path $wtSettingsPath) {
        Copy-Item $wtSettingsPath "$wtSettingsPath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')" -Force
    }

    Write-Info "Installing Windows Terminal settings..."
    Copy-Item ".\windows-terminal\settings.json" $wtSettingsPath -Force
    Write-Success "✓ Windows Terminal configured with Catppuccin Mocha theme"
} else {
    Write-Warning "⚠ Windows Terminal settings not found (skip)"
}

Write-Host ""

# Step 3: Setup Claude Code directories
Write-Info "━━━ STEP 3/7: Creating Claude Code directories ━━━"
Write-Host ""

$claudeDir = "$env:USERPROFILE\.claude"
$agentsDir = "$claudeDir\agents"

New-Item -ItemType Directory -Force -Path $agentsDir | Out-Null
Write-Success "✓ Created $agentsDir"

Write-Host ""

# Step 4: Copy Claude Code settings and agents
Write-Info "━━━ STEP 4/7: Installing Claude Code configuration ━━━"
Write-Host ""

if (Test-Path ".\claude\settings\settings.local.json") {
    Copy-Item ".\claude\settings\settings.local.json" "$claudeDir\settings.local.json" -Force
    Write-Success "✓ Installed Claude Code settings"
} else {
    Write-Warning "⚠ Claude settings not found (skip)"
}

if (Test-Path ".\claude\agents\*.md") {
    $agents = Get-ChildItem ".\claude\agents\*.md"
    Copy-Item ".\claude\agents\*.md" $agentsDir -Force
    Write-Success "✓ Installed $($agents.Count) custom Claude agents:"
    foreach ($agent in $agents) {
        Write-Host "   • $($agent.Name)" -ForegroundColor Gray
    }
} else {
    Write-Warning "⚠ Claude agents not found (skip)"
}

Write-Host ""

# Step 5: WSL2 Setup Script
Write-Info "━━━ STEP 5/7: Generating WSL2 setup script ━━━"
Write-Host ""

$wslSetupScript = @'
#!/bin/bash
# WSL2 Setup Script - Auto-generated by MEGA-INSTALLER
# This installs all tools inside your Ubuntu Linux environment

set -e

echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo "    WSL2 UBUNTU SETUP - Installing Dev Tools"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""

# Update system
echo "━━━ Updating Ubuntu packages ━━━"
sudo apt update -qq
sudo apt upgrade -y -qq

# Install essentials
echo ""
echo "━━━ Installing essential tools ━━━"
sudo apt install -y -qq \
    build-essential \
    curl \
    wget \
    git \
    vim \
    tmux \
    unzip \
    python3 \
    python3-pip \
    python3-venv

# Install Node.js via nvm
echo ""
echo "━━━ Installing Node.js (via nvm) ━━━"
if [ ! -d "$HOME/.nvm" ]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm use --lts
else
    echo "✓ nvm already installed"
fi

# Reload nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Install Claude Code
echo ""
echo "━━━ Installing Claude Code CLI ━━━"
npm install -g @anthropic-ai/claude-code

# Create directories
echo ""
echo "━━━ Setting up directories ━━━"
mkdir -p ~/.claude/agents

# Copy configs from Windows
echo ""
echo "━━━ Copying Claude configs from Windows ━━━"
WIN_USER=$(powershell.exe -Command "Write-Host \$env:USERNAME" | tr -d '\r')
WIN_CLAUDE_PATH="/mnt/c/Users/$WIN_USER/.claude"

if [ -f "$WIN_CLAUDE_PATH/settings.local.json" ]; then
    cp "$WIN_CLAUDE_PATH/settings.local.json" ~/.claude/
    echo "✓ Copied Claude settings"
fi

if [ -d "$WIN_CLAUDE_PATH/agents" ]; then
    cp "$WIN_CLAUDE_PATH/agents"/*.md ~/.claude/agents/ 2>/dev/null || true
    AGENT_COUNT=$(ls ~/.claude/agents/*.md 2>/dev/null | wc -l)
    echo "✓ Copied $AGENT_COUNT Claude agents"
fi

# Done!
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo "✅ WSL2 SETUP COMPLETE!"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "1. Authenticate Claude Code: claude auth login"
echo "2. Start coding: claude"
echo ""
echo "Your custom agents are ready to use!"
echo ""
'@

$wslSetupPath = "$env:TEMP\wsl-setup.sh"
$wslSetupScript | Out-File -FilePath $wslSetupPath -Encoding utf8 -NoNewline
Write-Success "✓ Created WSL2 setup script"

Write-Host ""

# Step 6: Run WSL2 setup
Write-Info "━━━ STEP 6/7: Running WSL2 setup (this takes ~5 minutes) ━━━"
Write-Host ""

try {
    # Copy script to WSL
    wsl -d Ubuntu bash -c "cat > /tmp/wsl-setup.sh" < $wslSetupPath
    wsl -d Ubuntu chmod +x /tmp/wsl-setup.sh

    # Run setup script
    Write-Info "Installing tools in Ubuntu (please wait)..."
    wsl -d Ubuntu bash /tmp/wsl-setup.sh

    Write-Success "✓ WSL2 setup complete"
} catch {
    Write-Error-Custom "✗ WSL2 setup failed: $_"
    Write-Info "You can run the setup manually later:"
    Write-Info "  wsl -d Ubuntu bash /tmp/wsl-setup.sh"
}

Write-Host ""

# Step 7: Final instructions
Write-Info "━━━ STEP 7/7: Final Steps ━━━"
Write-Host ""

Write-Host "Please complete these manual steps:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1️⃣  Install JetBrains Mono Font:" -ForegroundColor Yellow
Write-Host "   Download: https://www.jetbrains.com/lp/mono/"
Write-Host "   Extract ZIP, open fonts/ttf folder"
Write-Host "   Select all .ttf files → Right-click → 'Install for all users'"
Write-Host ""

Write-Host "2️⃣  Authenticate Claude Code in WSL2:" -ForegroundColor Yellow
Write-Host "   Run these commands:"
Write-Host "   > wsl -d Ubuntu" -ForegroundColor Cyan
Write-Host "   > claude auth login" -ForegroundColor Cyan
Write-Host ""

Write-Host "3️⃣  Restart Windows Terminal" -ForegroundColor Yellow
Write-Host "   Close all instances and reopen to see the new theme"
Write-Host ""

# Summary
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "✅ INSTALLATION COMPLETE!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""

Write-Success "What was installed:"
Write-Host "  ✓ WSL2 (Ubuntu Linux)"
Write-Host "  ✓ Node.js, Python, git, and dev tools"
Write-Host "  ✓ Claude Code CLI"
Write-Host "  ✓ Windows Terminal with Catppuccin theme"
Write-Host "  ✓ Claude Code settings and agents"
Write-Host ""

Write-Success "To start coding:"
Write-Host "  1. Open Windows Terminal"
Write-Host "  2. Select 'Ubuntu' profile"
Write-Host "  3. Run: claude auth login"
Write-Host "  4. Run: claude"
Write-Host ""

Write-Info "Enjoy your setup! 🚀"
Write-Host ""
