#!/bin/bash
# Quick test script to visualize the dev layout
# Usage: ./test-dev-layout.sh

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           TMUX DEV LAYOUT - QUICK START GUIDE                    ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Your three-pane development layout is now configured!"
echo ""
echo "┌──────────────────────────────┬──────────────────────────────┐"
echo "│                              │                              │"
echo "│         Claude Code          │      Terminal Editor         │"
echo "│       (Left Pane)            │      (Top-Right Pane)        │"
echo "│                              │                              │"
echo "│   - AI assistance            │   - vim/nvim/emacs           │"
echo "│   - Code review              │   - File editing             │"
echo "│   - Debugging help           │   - Code navigation          │"
echo "│                              │                              │"
echo "│                              ├──────────────────────────────┤"
echo "│                              │                              │"
echo "│                              │    Output / Logs / Tests     │"
echo "│                              │    (Bottom-Right Pane)       │"
echo "│                              │                              │"
echo "│                              │   - Test results             │"
echo "│                              │   - Build output             │"
echo "│                              │   - Server logs              │"
echo "└──────────────────────────────┴──────────────────────────────┘"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 TO CREATE THIS LAYOUT:"
echo "   Press: Ctrl-a then d"
echo ""
echo "🧭 NAVIGATION (Vim-style):"
echo "   Ctrl-a h/j/k/l  →  Move between panes"
echo ""
echo "📏 RESIZE PANES:"
echo "   Ctrl-a Shift-H/J/K/L  →  Fine adjustments (hold to repeat)"
echo "   Ctrl-a Shift-Arrow    →  Large adjustments"
echo ""
echo "🔍 QUICK ACTIONS:"
echo "   Ctrl-a z      →  Toggle zoom current pane"
echo "   Ctrl-a e      →  Zoom to editor pane"
echo "   Ctrl-a Shift-O →  Zoom to output pane"
echo "   Ctrl-a Shift-C →  Clear right panes"
echo ""
echo "📚 FULL GUIDE:"
echo "   cat ~/.tmux/TMUX_DEV_LAYOUT_GUIDE.md"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Configuration files:"
echo "   • ~/.tmux.conf (main config)"
echo "   • ~/.tmux/scripts/dev-layout-startup.sh (auto-startup)"
echo "   • ~/.tmux/TMUX_DEV_LAYOUT_GUIDE.md (this guide)"
echo ""
echo "Ready to start? Run: tmux"
echo "Or auto-start on terminal launch by adding to ~/.zshrc:"
echo "   if command -v tmux &> /dev/null && [ -z \"\$TMUX\" ]; then"
echo "       ~/.tmux/scripts/dev-layout-startup.sh"
echo "   fi"
echo ""
